[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hunyo-capture"
dynamic = ["version"]
description = "Lightweight capture layer for marimo notebook instrumentation"
authors = [{name = "Your Name", email = "your.email@example.com"}]
license = {text = "MIT"}
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.0.0",
]

[project.optional-dependencies]
test = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "pytest-timeout>=2.1.0",
    "pytest-asyncio>=0.21.0",
    "marimo>=0.8.0",
]

[tool.hatch.version]
path = "src/hunyo_capture/constants.py"

[tool.hatch.envs.test]
dependencies = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "pytest-timeout>=2.1.0",
    "pytest-asyncio>=0.21.0",
    "marimo>=0.8.0",
]

[tool.hatch.envs.test.scripts]
test = "pytest {args}"
test-cov = "pytest --cov=src/hunyo_capture --cov-report=term-missing {args}"

[tool.hatch.build.targets.wheel]
packages = ["src/hunyo_capture"] 